import RestReducer from 'redux-rest-reducer';
import { ACTIONS } from '../actions/skills';

export default RestReducer({
  GET: ACTIONS.GET,
  GET_SUCCESS: ACTIONS.GET_SUCCESS,
  GET_FAILURE: ACTIONS.GET_FAILURE,
  GET_ALL: ACTIONS.GET_ALL,
  GET_ALL_SUCCESS: ACTIONS.GET_ALL_SUCCESS,
  POST: ACTIONS.POST,
  POST_SUCCESS: ACTIONS.POST_SUCCESS,
  PUT: ACTIONS.PUT,
  PUT_SUCCESS: ACTIONS.PUT_SUCCESS,
  PUT_FAILURE: ACTIONS.PUT_FAILURE,
  DELETE: ACTIONS.DELETE,
  DELETE_SUCCESS: ACTIONS.DELETE_SUCCESS,
  DELETE_FAILURE: ACTIONS.DELETE_FAILURE,
});
